- name: Tag & Push Docker image
  run: |
    IMAGE=${{ secrets.DOCKER_USERNAME }}/my-app:latest
    docker tag my-app $IMAGE
    docker push $IMAGE

- name: Deploy lên VPS qua SSH
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USER }}
    password: ${{ secrets.VPS_PASSWORD }}
    port: ${{ secrets.VPS_PORT }}
    script: |
      IMAGE=${{ secrets.DOCKER_USERNAME }}/my-app:latest
      docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      docker pull $IMAGE
      docker stop my-app || true
      docker rm my-app || true
      docker run -d \
        --name my-app \
        -p 8080:8080 \
        --restart unless-stopped \
        $IMAGE
